paasta 3.0

diff --git a/paasta-controller/src/capi-release/packages/cloud_controller_ng/pre_packaging b/paasta-controller/src/capi-release/packages/cloud_controller_ng/pre_packaging
--- a/paasta-controller/src/capi-release/packages/cloud_controller_ng/pre_packaging
+++ b/paasta-controller/src/capi-release/packages/cloud_controller_ng/pre_packaging
@@ -2,7 +2,21 @@ set -e -x
 
 cd ${BUILD_DIR}/capi-release/src/cloud_controller_ng
 
-BUNDLE_WITHOUT=development:test bundle package --all --no-install --path ./vendor/cache
+set +e
+for i in {1..3}; do
+  BUNDLE_WITHOUT=development:test bundle package --all --no-install --path ./vendor/cache
+  exit_code="$?"
+
+  if [ "${exit_code}" == "0" ]; then
+    break
+  fi
+  sleep 1
+done
+set -e
+if [ "${exit_code}" != "0" ]; then
+  echo "ERROR: Failed to run 'bundle package' after 3 attempts"
+  exit "${exit_code}"
+fi
 
 rm -rf ./vendor/cache/ruby
 rm -rf ./vendor/cache/vendor
diff --git a/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_ctl.erb b/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_ctl.erb
--- a/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_ctl.erb
+++ b/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_ctl.erb
@@ -7,40 +7,18 @@ function main() {
   local action
   action="${1}"
 
-  local pgversion
-  pgversion="postgres-9.4.9"
-
-  JOB_DIR=/var/vcap/jobs/postgres
-  PACKAGE_DIR="/var/vcap/packages/${pgversion}"
-  STORE_DIR=/var/vcap/store
-  DATA_DIR="${STORE_DIR}/${pgversion}"
-
-  PACKAGE_DIR_OLD=/var/vcap/packages/postgres-unknown
-  DATA_DIR_OLD="${STORE_DIR}/postgres-unknown"
-
-  if [[ -d "${STORE_DIR}/postgres-9.4.6" ]]; then
-    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.6"
-    PACKAGE_DIR_OLD=/var/vcap/packages/postgres-9.4.6
-  fi
-
-  if [[ -d "${STORE_DIR}/postgres-9.4.5" ]]; then
-    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.5"
-    PACKAGE_DIR_OLD=/var/vcap/packages/postgres-9.4.5
-  fi
-
-  RUN_DIR=/var/vcap/sys/run/postgres
-  LOG_DIR=/var/vcap/sys/log/postgres
-
-  # external_pid_file in postgresql.conf takes care of
-  # overwriting $PIDFILE with actual DB server pid
-  PIDFILE="${RUN_DIR}/postgres.pid"
-
+  source /var/vcap/jobs/postgres/bin/pgconfig.sh
   set +u
   source /var/vcap/packages/postgres-common/utils.sh
   set -u
 
   case "${action}" in
     "start")
+      if [ -d $DATA_DIR -a -f $POSTGRES_UPGRADE_LOCK ]; then
+        echo "FAIL: DB upgrade stopped in the middle, manual intervention required, quitting..."
+        exit 1
+      fi
+
       if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
         set +e
         "${PACKAGE_DIR}/bin/pg_ctl" stop -m fast -w -D ${DATA_DIR}
@@ -67,22 +45,27 @@ function main() {
 
     "stop")
       echo "Stopping PostgreSQL: "
+      for dir in ${pgversion_older} ${pgversion_old} ${pgversion_current}; do
+        if [ -d "${STORE_DIR}/${dir}" -a -f "${STORE_DIR}/${dir}/postgresql.conf" ]; then
+          set +e
+          su - vcap -c "${PACKAGE_DIR}/${dir}/bin/pg_ctl stop -m fast -w -D ${STORE_DIR}/${dir}"
+          set -e
+        fi
+      done
+
       if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
         set +e
          su - vcap -c "${PACKAGE_DIR_OLD}/bin/pg_ctl stop -m fast -w -D ${DATA_DIR_OLD}"
         set -e
       fi
 
+      set +e
       su - vcap -c "${PACKAGE_DIR}/bin/pg_ctl stop -m fast -w -D ${DATA_DIR}"
+      set -e
 
       set +u
       wait_pidfile "${PIDFILE}"
       set -u
-
-      ;;
-
-    "status")
-      su - vcap -c "${PACKAGE_DIR}/bin/pg_ctl status -D ${DATA_DIR}"
 
       ;;
 
diff --git a/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_start.sh.erb b/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_start.sh.erb
--- a/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_start.sh.erb
+++ b/paasta-controller/src/postgres-release/jobs/postgres/templates/postgres_start.sh.erb
@@ -1,36 +1,8 @@
 #!/bin/bash -exu
 
 function main() {
-  local pgversion
-  pgversion="postgres-9.4.9"
-
-  JOB_DIR=/var/vcap/jobs/postgres
-  PACKAGE_DIR="/var/vcap/packages/${pgversion}"
-  STORE_DIR=/var/vcap/store
-  DATA_DIR="${STORE_DIR}/${pgversion}"
-
-  DATA_DIR_PREVIOUS="${STORE_DIR}/postgres-previous"
-  DATA_DIR_OLD="${STORE_DIR}/postgres-unknown"
-
-  if [ -d "${STORE_DIR}/postgres-9.4.6" -a -f "${STORE_DIR}/postgres-9.4.6/postgresql.conf" ]; then
-    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.6"
-  fi
-
-  if [ -d "${STORE_DIR}/postgres-9.4.5" -a -f "${STORE_DIR}/postgres-9.4.5/postgresql.conf" ]; then
-    DATA_DIR_OLD="${STORE_DIR}/postgres-9.4.5"
-  fi
-
-  RUN_DIR=/var/vcap/sys/run/postgres
-  PIDFILE="${RUN_DIR}/postgres.pid"
-
-  HOST="0.0.0.0"
-  PORT="<%= p("databases.port") %>"
-
-  if [[ -n "${LD_LIBRARY_PATH:-}" ]]; then
-    LD_LIBRARY_PATH="${PACKAGE_DIR}/lib:${LD_LIBRARY_PATH}"
-  else
-    LD_LIBRARY_PATH="${PACKAGE_DIR}/lib"
-  fi
+  source /var/vcap/jobs/postgres/bin/pgconfig.sh
+  source /var/vcap/jobs/postgres/bin/utils.sh
 
   if [ ! -d "${STORE_DIR}" ]; then
     echo "ERROR: storage directory doesn't exist"
@@ -38,24 +10,9 @@ function main() {
     exit 1
   fi
 
-  if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
-    pushd "${DATA_DIR_PREVIOUS}" > /dev/null
-      if [ -a "postgresql.conf" ]; then
-        rm -r *
-      fi
-    popd > /dev/null
-
-    pushd "${DATA_DIR_OLD}" > /dev/null
-      cp -r * "${DATA_DIR}"
-    popd > /dev/null
-
-    pushd "${DATA_DIR_OLD}" > /dev/null
-      cp -r * "${DATA_DIR_PREVIOUS}"
-    popd > /dev/null
-
-    pushd "${DATA_DIR_OLD}" > /dev/null
-      rm -r *
-    popd > /dev/null
+  if [ -d $DATA_DIR -a -f $POSTGRES_UPGRADE_LOCK ]; then
+    echo "FAIL: DB upgrade stopped in the middle, manual intervention required, quitting..."
+    exit 1
   fi
 
   if [ ! -f "${DATA_DIR}/postgresql.conf" ]; then
@@ -65,7 +22,35 @@ function main() {
     mkdir -p "${DATA_DIR}/pg_log"
   fi
 
-  cp "${JOB_DIR}/config/postgresql.conf" "${JOB_DIR}/config/pg_hba.conf" "${DATA_DIR}"
+  if [ -d "${DATA_DIR_OLD}" -a -f "${DATA_DIR_OLD}/postgresql.conf" ]; then
+    rm -rf ${DATA_DIR_PREVIOUS}
+    if is_major; then
+      echo "Running a PostgreSQL major upgrade from ${pgversion_upgrade_from} to ${pgversion_current}"
+      touch "$POSTGRES_UPGRADE_LOCK"
+      # Move to a directory writeable by vcap user
+      mkdir -p "${PG_STORE_DIR}/pg_upgrade_tmp"
+      pushd "${PG_STORE_DIR}/pg_upgrade_tmp"
+        "${PACKAGE_DIR}/bin/pg_upgrade" \
+          --old-datadir "${DATA_DIR_OLD}" \
+          --new-datadir "${DATA_DIR}" \
+          --old-bindir "${PACKAGE_DIR_OLD}/bin" \
+          --new-bindir "${PACKAGE_DIR}/bin"
+      popd
+      rm -f "${POSTGRES_UPGRADE_LOCK}"
+    else
+      echo "Running a PostgreSQL minor upgrade from ${pgversion_upgrade_from} to ${pgversion_current}"
+      mkdir -p "${DATA_DIR}"
+      chown -R vcap:vcap "${DATA_DIR}"
+      chmod 700 "${DATA_DIR}"
+
+      pushd "${DATA_DIR_OLD}" > /dev/null
+        cp -r * "${DATA_DIR}"
+      popd > /dev/null
+    fi
+    mv "${DATA_DIR_OLD}" "${DATA_DIR_PREVIOUS}"
+  fi
+
+  cp "${JOB_DIR}/config/postgresql.conf" "${JOB_DIR}/config/pg_hba.conf" "${JOB_DIR}/config/pg_ident.conf" "${DATA_DIR}"
 
   echo "Starting PostgreSQL: "
   "${PACKAGE_DIR}/bin/pg_ctl" -o "-h ${HOST} -p ${PORT}" \
@@ -77,72 +62,5 @@ function main() {
   create_databases
 }
 
-function pgexec() {
-  local database
-  database="${1}"
-
-  local command
-  command="${2}"
-
-  "${PACKAGE_DIR}/bin/psql" \
-    -U "vcap" \
-    -p "${PORT}" \
-    -d "${database}" \
-    -c "${command}"
-}
-
-function create_roles() {
-  echo "Creating roles..."
-  <% p("databases.roles", []).each do |role| %>
-    echo "Trying to create role <%= role["name"] %>..."
-    set +e
-    # TODO remove unused roles automatically
-    # Default permissions are: nosuperuser nologin inherit nocreatedb.
-    # Will fail if role already exists, which is OK
-    pgexec postgres "CREATE ROLE \"<%= role["name"] %>\""
-    set -e
-
-    echo "Setting password for role <%= role["name"] %>..."
-    pgexec postgres "ALTER ROLE \"<%= role["name"] %>\" WITH LOGIN PASSWORD '<%= role["password"] %>'"
-
-    <% if role["permissions"] %>
-      echo "Adding permissions <%= role["permissions"].join(' ') %> for role <%= role["name"] %>..."
-      pgexec postgres "ALTER ROLE \"<%= role["name"] %>\" WITH <%= role["permissions"].join(' ') %>"
-    <% end %>
-  <% end %>
-}
-
-function create_databases() {
-  echo "Creating databases..."
-  <% p("databases.databases", []).each do |database| %>
-    echo "Trying to create database <%= database["name"] %>..."
-    set +e
-    "${PACKAGE_DIR}/bin/createdb" "<%= database["name"] %>" -p ${PORT}
-    set -e
-
-    <% if database["citext"] %>
-      echo "Trying to install citext..."
-      set +e
-      pgexec "<%= database["name"] %>" "CREATE EXTENSION citext"
-      pgexec "<%= database["name"] %>" "CREATE EXTENSION citext FROM UNPACKAGED"
-      set -e
-    <% end %>
-
-    echo "Enabling pgcrypto extension..."
-    pgexec "<%= database["name"] %>" "CREATE EXTENSION IF NOT EXISTS pgcrypto"
-
-
-    <% if p("databases.collect_statement_statistics") %>
-      echo "Enabling pg_stat_statements extension..."
-      pgexec "<%= database["name"] %>" "CREATE EXTENSION IF NOT EXISTS pg_stat_statements"
-    <% end %>
-
-    <% if database["run_on_every_startup"] %>
-      <% database["run_on_every_startup"].each do |query| %>
-        pgexec "<%= database["name"] %>" "<%= query %>"
-      <% end %>
-    <% end %>
-  <% end %>
-}
 
 main
